name = "TenXData"
uuid = "068dec19-929c-41c0-935f-50650e5a4e0c"
authors = ["Matt Karikomi <mattkarikomi@gmail.com> and contributors"]
repo = "https://github.com/mkarikom/TenXData.jl.git"
version = "1.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
DataFrames = "0.22"
TranscodingStreams = "0.9"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
